workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build


orbs:
  ruby: circleci/ruby@2.0.1

jobs:
  build:
    working_directory: ~/todo_list
    docker:
      - image: cimg/ruby:3.2.3-node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: hello
          command: echo hello
  deploy:
    docker:
      - image: cimg/ruby:3.2.3-node
    steps:
      - run:
          name: world
          command: echo world
